sudo: required
Services:
        - docker
before_install:
        - docker build -t project:v2 -f Dockerfile .
script:
        - docker run project:v2 npm run test -- --coverage
deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "Appala-Project"
        env: "Dev-env"
        bucket_name: "elasticbeanstalk-us-east-2-902836866638"
        bucket_path: "Appala-Project"
        on:
                branch: master
        access_key_id: $Access_key
        secret_access_key: $Secret_key
